[features]
seeds = true
skip-lint = false

[programs.mainnet]
launchpad = "CdvaU5g7hV3B7amC149moLDfGrMsXmJwqRm3uVCoMdZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node tests/launchpad.js"

