[features]
seeds = true
skip-lint = false

[programs.devnet]
launchpad = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node tests/launchpad.js"
