name: anchor-ci

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          solana --version

      - name: Install Anchor CLI
        run: |
          sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev libudev-dev
          cargo install --git https://github.com/coral-xyz/anchor anchor-cli --tag v0.30.1 --locked
          echo "ANCHOR_VERSION=$(anchor --version)"

      - name: Build Anchor program
        env:
          PATH: ${{ env.PATH }}:$HOME/.local/share/solana/install/active_release/bin
        run: |
          anchor --version
          anchor build
